### ISSUE TITLE
bug: sidebar

### ISSUE THREAD

**Issue by onkar95** [onkar95/BE-project-mainfront#2]
siderbar losses its original form after adding test section -Home 

this becomes
![Screenshot (64)](https://user-images.githubusercontent.com/66904041/234309745-cdd27ac8-bfbe-4055-94ae-3a4975f1434a.png)
this
![Screenshot (65)](https://user-images.githubusercontent.com/66904041/234310457-7e28dc71-1a73-48fb-80d3-408dfe95de1e.png)

**Comment by onkar95** [comment]
@MayurSMahajan  please look into it 🙂

**Comment by MayurSMahajan** [comment]
@onkar95 on it
